package CodeGenerator;

import java.io.*;
import java.util.*;

import Tuga.*;
import ConstantPool.ConstantPool;
import VM.OpCode;
import VM.Instruction.*;
import org.antlr.v4.runtime.tree.ParseTree;

/**
 * CodeGen is a visitor class that generates bytecode for the Tuga programming language.
 * It extends the TugaBaseVisitor class and implements the visit methods for various grammar rules.
 * The generated bytecode is stored in a list of Instruction objects.
 */
public class CodeGen extends TugaBaseVisitor<Void> {
    /**
     * List de estruturas de dados pre-definidas no Compilador.
     *
     * @param code,typeChecker,constantPool
     */
    private final ArrayList<Instruction> code = new ArrayList<>();
    private final TypeChecker typeChecker;
    private ConstantPool constantPool = new ConstantPool();

    // ___________BUILDERS_________________

    /**
     * Construtor da classe CodeGen.
     *
     * @param checker      TypeChecker para verificar os tipos das expressões.
     * @param constantPool ConstantPool para armazenar constantes.
     */
    public CodeGen(TypeChecker checker, ConstantPool constantPool) {
        this.typeChecker = checker;
        this.constantPool = constantPool;
    }


    //   ____________VISITORS__________________

    /**
     * Visita o nó expr e verifica o tipo do mesmo.
     * Converte para o tipo pretendido
     *
     * @param expr, target O nó a visitar e o tipo alvo.
     */
    private void visitAndConvert(ParseTree expr, Tipo target) {
        visit(expr);
        Tipo origem = typeChecker.getTipo(expr);
        if (origem != target) emitConversion(origem, target);
    }

    /**
     * Visita o nó Prog e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó raiz do programa.
     * @return null
     */
    @Override
    public Void visitProg(TugaParser.ProgContext ctx) {
        visitChildren(ctx);
        emit(OpCode.halt);
        return null;
    }

    /**
     * Visita o nó de Stat e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitVarDeclaration(TugaParser.VarDeclarationContext ctx) {
        return visitChildren(ctx);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitAfetacao(TugaParser.AfetacaoContext ctx) {
        return visitChildren(ctx);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitBloco(TugaParser.BlocoContext ctx) {
        return visitChildren(ctx);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitEquanto(TugaParser.EquantoContext ctx) {
        return visitChildren(ctx);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitSe(TugaParser.SeContext ctx) {
        return visitChildren(ctx);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitEscreve(TugaParser.EscreveContext ctx) {
        visit(ctx.expr());
        Tipo tipo = typeChecker.getTipo(ctx.expr());
        if (tipo == Tipo.ERRO) {
            System.err.println("Erro de tipo na expressão.");
            return null;
        }
        switch (tipo) {
            case INT -> emit(OpCode.iprint);
            case REAL -> emit(OpCode.dprint);
            case BOOL -> emit(OpCode.bprint);
            case STRING -> emit(OpCode.sprint);
            default -> System.err.println("Tipo invalido para impressao.");
        }
        return null;
    }

    /**
     * {@inheritDoc}
     *
     * <p>The default implementation returns the result of calling
     * {@link #visitChildren} on {@code ctx}.</p>
     */
    @Override
    public Void visitVazia(TugaParser.VaziaContext ctx) {

        return null; //retorna null ou continua a visitar a arvore e depois devolve o erro?
    }

    @Override
    public Void visitVar(TugaParser.VarContext ctx) {

        return null;
    }

    /**
     * Visita o nó de Stat e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */

   /* @Override
    public Void visitStat(TugaParser.StatContext ctx) {
        visit(ctx.expr());
        Tipo tipo = typeChecker.getTipo(ctx.expr());
        if (tipo == Tipo.ERRO) {
            System.err.println("Erro de tipo na expressão.");
            return null;
        }
        switch (tipo) {
            case INT -> emit(OpCode.iprint);
            case REAL -> emit(OpCode.dprint);
            case BOOL -> emit(OpCode.bprint);
            case STRING -> emit(OpCode.sprint);
            default -> System.err.println("Tipo invalido para impressao.");
        }
        return null;
    }
*/

    /**
     * Visita o nó de Inteiros e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitInt(TugaParser.IntContext ctx) {
        emit(OpCode.iconst, Integer.parseInt(ctx.getText()));
        return null;
    }

    /**
     * Visita o nó de Reais e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitReal(TugaParser.RealContext ctx) {
        double val = Double.parseDouble(ctx.getText());
        int index = constantPool.addDouble(val);
        emit(OpCode.dconst, index);
        return null;
    }

    /**
     * Visita o nó de Booleanos e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitBool(TugaParser.BoolContext ctx) {
        if (ctx.getText().equals("verdadeiro")) emit(OpCode.tconst);
        else if (ctx.getText().equals("falso")) emit(OpCode.fconst);
        return null;
    }

    /**
     * Visita o nó de String e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */

    @Override
    public Void visitString(TugaParser.StringContext ctx) {
        String text = ctx.getText().substring(1, ctx.getText().length() - 1); // remove aspas
        int index = constantPool.addString(text);
        emit(OpCode.sconst, index);
        return null;
    }

    /**
     * Visita o nó de Parens e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitParens(TugaParser.ParensContext ctx) {
        visit(ctx.expr());
        return null;
    }

    /**
     * Visita o nó de Unary e gera o bytecode correspondente.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitUnary(TugaParser.UnaryContext ctx) {
        visit(ctx.expr());
        Tipo tipo = typeChecker.getTipo(ctx);
        if (ctx.op.getType() == TugaParser.MINUS) {
            if (tipo == Tipo.INT) emit(OpCode.iuminus);
            else if (tipo == Tipo.REAL) emit(OpCode.duminus);
            else System.out.println("Erro: operação - inválida para tipo " + tipo);
        } else if (ctx.op.getType() == TugaParser.NOT) {
            if (tipo == Tipo.BOOL) emit(OpCode.not);
            else System.out.println("Erro: operação NOT inválida para tipo " + tipo);
        }
        return null;
    }

    /**
     * Visita o nó de AddSub e gera o bytecode para adiçao e subtraçao.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitAddSub(TugaParser.AddSubContext ctx) {
        Tipo tipo = typeChecker.getTipo(ctx);

        if (tipo == Tipo.ERRO) {
            System.err.println("Erro de tipo na expressão.");
            return null;
        }
        String op = ctx.op.getText();
        switch (tipo) {
            case INT -> {
                visitAndConvert(ctx.expr(0), tipo);
                visitAndConvert(ctx.expr(1), tipo);
                if (op.equals("+")) emit(OpCode.iadd);
                else if (op.equals("-")) emit(OpCode.isub);
            }
            case REAL -> {
                visitAndConvert(ctx.expr(0), tipo);
                visitAndConvert(ctx.expr(1), tipo);
                if (op.equals("+")) emit(OpCode.dadd);
                else if (op.equals("-")) emit(OpCode.dsub);
            }
            case STRING -> {
                if (op.equals("+")) {
                    visitAndConvert(ctx.expr(0), Tipo.STRING);
                    visitAndConvert(ctx.expr(1), Tipo.STRING);
                    emit(OpCode.sconcat);
                }
            }
            default -> System.err.println("Erro: tipo não suportado em AddSub");
        }
        return null;
    }

    /**
     * Visita o nó de MulDiv e gera o bytecode para multiplicação, divisão e módulo.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitMulDiv(TugaParser.MulDivContext ctx) {
        Tipo tipo = typeChecker.getTipo(ctx);
        visitAndConvert(ctx.expr(0), tipo);
        visitAndConvert(ctx.expr(1), tipo);
        if (tipo == Tipo.ERRO) {
            System.err.println("Erro de tipo na expressão.");
            return null;
        }
        String op = ctx.op.getText();
        switch (tipo) {
            case INT -> {
                switch (op) {
                    case "*" -> emit(OpCode.imult);
                    case "/" -> emit(OpCode.idiv);
                    case "%" -> emit(OpCode.imod);
                }
            }
            case REAL -> {
                switch (op) {
                    case "*" -> emit(OpCode.dmult);
                    case "/" -> emit(OpCode.ddiv);
                    case "%" -> emit(OpCode.dmod);
                }
            }
            default -> System.err.println("Erro: tipo não suportado em MulDiv");
        }
        return null;
    }

    /**
     * Visita o nó de And e gera o bytecode correspondente para And.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitAnd(TugaParser.AndContext ctx) {
        visitAndConvert(ctx.expr(0), Tipo.BOOL);
        visitAndConvert(ctx.expr(1), Tipo.BOOL);
        emit(OpCode.and);
        return null;
    }

    /**
     * Visita o nó de Or e gera o bytecode correspondente para Or.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */

    @Override
    public Void visitOr(TugaParser.OrContext ctx) {
        visitAndConvert(ctx.expr(0), Tipo.BOOL);
        visitAndConvert(ctx.expr(1), Tipo.BOOL);
        emit(OpCode.or);
        return null;
    }

    /**
     * Visita o nó de Relational e gera o bytecode correspondente para operações relacionais.
     *
     * @param ctx O contexto do nó de atribuição.
     * @return null
     */
    @Override
    public Void visitRelational(TugaParser.RelationalContext ctx) {
        Tipo t1 = typeChecker.getTipo(ctx.expr(0));
        Tipo t2 = typeChecker.getTipo(ctx.expr(1));

        Tipo tipoFinal;
        if (t1 == Tipo.REAL || t2 == Tipo.REAL) tipoFinal = Tipo.REAL;
        else if (t1 == Tipo.INT && t2 == Tipo.INT) tipoFinal = Tipo.INT;
        else if (t1 == Tipo.STRING && t2 == Tipo.STRING) tipoFinal = Tipo.STRING;
        else if (t1 == Tipo.BOOL && t2 == Tipo.BOOL) tipoFinal = Tipo.BOOL;
        else {
            System.err.println("Tipos incompatíveis em Relational");
            return null;
        }

        String op = ctx.op.getText();

        switch (tipoFinal) {
            case INT: {
                switch (op) {
                    // Trocar a ordem das visitas para evitar conversões desnecessárias
                    // (0)'<'(1) == (1)'>='(0) , (0)'<='(1) == (1)'>'(0)
                    case "<":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.ilt);
                        break;
                    case ">":
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        emit(OpCode.ilt);
                        break;
                    case "<=":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.ileq);
                        break;
                    case ">=":
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        emit(OpCode.ileq);
                        break;
                    case "igual":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.ieq);
                        break;
                    case "diferente":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.ineq);
                        break;
                    default:
                        erroOpRel(op);
                }
                break;
            }
            case REAL: {
                switch (op) {
                    // Trocar a ordem das visitas para evitar conversões desnecessárias
                    // (0)'<'(1) == (1)'>='(0) , (0)'<='(1) == (1)'>'(0)
                    case "<":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.dlt);
                        break;
                    case ">":
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        emit(OpCode.dlt);
                        break;
                    case "<=":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.dleq);
                        break;
                    case ">=":
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        emit(OpCode.dleq);
                        break;
                    case "igual":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.deq);
                        break;
                    case "diferente":
                        visitAndConvert(ctx.expr(0), tipoFinal);
                        visitAndConvert(ctx.expr(1), tipoFinal);
                        emit(OpCode.dneq);
                        break;
                    default:
                        erroOpRel(op);
                }
                break;
            }
            case STRING: {
                visitAndConvert(ctx.expr(0), tipoFinal);
                visitAndConvert(ctx.expr(1), tipoFinal);
                switch (op) {
                    case "igual" -> emit(OpCode.seq);
                    case "diferente" -> emit(OpCode.sneq);
                    default -> erroOpRel(op);
                }
                break;
            }
            case BOOL: {
                visitAndConvert(ctx.expr(0), tipoFinal);
                visitAndConvert(ctx.expr(1), tipoFinal);
                switch (op) {
                    case "igual" -> emit(OpCode.beq);
                    case "diferente" -> emit(OpCode.bneq);
                    default -> erroOpRel(op);
                }
                break;
            }

        }

        return null;
    }

    //____________________ METODOS AUXILIARES______________________
    private void erroOpRel(String op) {
        System.err.println("Operação relacional inválida: " + op);
    }

    /**
     * Fução auxiliar para emitir a conversão de tipos.
     *
     * @param de, para. O tipo de origem e o tipo de destino.
     * @return null
     */
    private void emitConversion(Tipo de, Tipo para) {
        if (de == para) return;
        switch (de) {
            case INT -> {
                if (para == Tipo.REAL) emit(OpCode.itod);
                else if (para == Tipo.STRING) emit(OpCode.itos);
            }
            case REAL -> {
                if (para == Tipo.STRING) emit(OpCode.dtos);
            }
            case BOOL -> {
                if (para == Tipo.STRING) emit(OpCode.btos);
            }
            default -> System.err.println("Conversão não suportada: " + de + " -> " + para);
        }
    }

    /**
     * Emite uma instrução de bytecode.
     *
     * @param opc O código da operação a emitir.
     */
    public void emit(OpCode opc) {
        code.add(new Instruction(opc));
    }

    /**
     * Emite uma instrução de bytecode com um argumento.
     *
     * @param opc O código da operação a emitir.
     * @param val O valor do argumento.
     */
    public void emit(OpCode opc, int val) {
        code.add(new Instruction1Arg(opc, val));
    }

    public void dumpCode() {
        System.out.println("*** Instructions ***");
        for (int i = 0; i < code.size(); i++)
            System.out.println(i + ": " + code.get(i));
    }

    public void saveBytecodes(String filename) throws IOException {
        try (DataOutputStream dout = new DataOutputStream(new FileOutputStream(filename))) {
            for (Instruction inst : code)
                inst.writeTo(dout);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public List<Instruction> getCode() {
        return code;
    }

    /*
     * private int addToConstantPool(Object value) {
     * int index = constantPool.indexOf(value);
     * if (index != -1) {
     * return index;
     * }
     * constantPool.add(value);
     * return constantPool.size() - 1;
     * }
     *
     * public Object getConstant(int index) {
     * if (index >= 0 && index < constantPool.size()) {
     * return constantPool.get(index);
     * }
     * return null;
     * }
     */

}